CREATE TABLE IF NOT EXISTS Adresse 
(id INTEGER PRIMARY KEY AUTOINCREMENT, &_
BL_id INTEGER , LK_id INTEGER, Stadt_id INTEGER, PLZ_id INTEGER, & _
Info TEXT NOT NULL, & _
Comment TEXT)

CREATE TABLE IF NOT EXISTS BundesLand 
(id INTEGER PRIMARY KEY AUTOINCREMENT, & _
name TEXT NOT NULL, & _
comments TEXT)

CREATE TABLE IF NOT EXISTS LandKreis 
(id INTEGER PRIMARY KEY AUTOINCREMENT, & _
name TEXT NOT NULL, & _
comments TEXT)

CREATE TABLE IF NOT EXISTS PLZ 
(id INTEGER PRIMARY KEY AUTOINCREMENT, & _
PLZ INTEGER NOT NULL, & _
comments TEXT)

CREATE TABLE IF NOT EXISTS Stadt 
(id INTEGER PRIMARY KEY AUTOINCREMENT, & _
BL_id INTEGER, LK_id INTEGER, PLZ_id INTEGER, & _
Stadt_name TEXT NOT NULL, & _
Stadt_comments TEXT)

CREATE TABLE IF NOT EXISTS Strasse 
(id INTEGER PRIMARY KEY AUTOINCREMENT, & _
name TEXT NOT NULL, & _
comments TEXT)